Added Dockerfile and Docker Compose files for project initialization.
DhanushNehru/CustomCodeEditor pull request #75
Opened 2024-06-22 13:46 UTC by Chaitanya1672

Resolves #74 
### PR Fixes:
1. Added `Dockerfile` to create an image of our project for containerization.
2. Added `docker-compose.yml` file for quick project initialization.

### Checklist before requesting a review
- [x] I have pull latest changes from `main` branch
- [x] I have tested the changes locally
- [x] I have run `npm run lint:fix` locally
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

2024-06-22 14:07 UTC, DhanushNehru requested changes
Hi @Chaitanya1672 can you update the README.md file for the setup instead of merging the .env.example sample file

2024-06-22 14:22 UTC, Chaitanya1672 commented
> Hi @Chaitanya1672 can you update the README.md file for the setup instead of merging the .env.example sample file

I have created pull request for updating steps in readme.md file, do you want me to delete `.env.example` file from first PR, IMO I think it is good to have one example env file where user can easily copy keys to `.env`

2024-06-22 18:47 UTC, DhanushNehru approved these changes

2024-06-23 17:49 UTC, DhanushNehru approved these changes

2024-06-23 17:49 UTC, merged